---
# ansible-playbook -v 001.requirements.yml -u root
- name: "Installing required ansible galaxy packages"
  gather_facts: no
  hosts: localhost
  become: no
  tasks:
    - name: "Install Ansible roles for GlusterFS"
      shell: "ansible-galaxy install -p $HOME/.ansible/roles -r requirements.yml --force"

    - name: "Install Ansible galaxy collection for GlusterFS volume support"
      shell: "ansible-galaxy collection install -p $HOME/.ansible/roles gluster.gluster --force"

    - name: "Installing Jmespath through pip3"
      pip:
        name: jmespath
        state: present
        executable: pip3
