---
# ansible-playbook -v 003.setup_glusterfs_cluster.yml -u root
- hosts: all
  become: yes
  become_user: root
  gather_facts: True

  # Install glusterfs-server before running the tasks of
  # gluster.cluster role
  pre_tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: http://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/rsa.pub
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: Add an RPM signing key, uses whichever key is at the URL
      rpm_key:
        key: http://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/rsa.pub
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Add new apt source
      
      apt_repository:
        repo: ppa:gluster/glusterfs-{{ glusterd_version }}
        filename: gluster.list
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: Add yum apt source
      yum_repository:
        name: glusterfs
        description: glusterfs YUM repo
        baseurl: https://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/LATEST/RHEL/glusterfs-rhel8.repo
      when: ansible_os_family == 'RedHat'

    - name: Update repositories cache and install "glusterfs-server" package
      package:
        name: "{{item}}"
        update_cache: yes
      loop:
        - "glusterfs-server"
        
    - name: Set python path symlink
      file:
        src: "/usr/bin/python3"
        dest: "/usr/bin/python"
        state: link
    # Pause for 5 seconds to build  cache.
    - name: Pause for 5 seconds to build  cache
      pause:
        seconds: 5
        
    - debug:
        var: gluster_cluster_hosts
  
  vars:
    # The transport type for the volume (tcp / rdma / tcp,rdma)
    gluster_cluster_transport: 'tcp,rdma'
    # Force option will be used while creating a volume, any warnings will be suppressed.
    gluster_cluster_force: 'yes'
    # Brick paths on servers. Multiple brick paths can be separated by commas.
    gluster_cluster_bricks: '/mnt/brick1'

    # Replica count while creating a volume. Currently replica 2 and replica 3 are supported.
    #gluster_cluster_replica_count: '2'

  roles:
     - gluster.cluster
