---
# ansible-playbook -v 004.mount_glusterfs.yml -u root
- hosts: all
  become: yes
  become_user: root
  gather_facts: True

  tasks:
    # Install glusterfs-client
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: http://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/rsa.pub
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add new apt source
      apt_repository:
        repo: ppa:gluster/glusterfs-{{ glusterd_version }}
        filename: gluster.list
        state: present
      when: ansible_os_family == 'Debian'

      # Install glusterfs-client
    - name: Add an RPM signing key, uses whichever key is at the URL
      rpm_key:
        key: http://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/rsa.pub
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Add new yum source
      yum_repository:
        name: glusterfs
        description: glusterfs YUM repo
        baseurl: https://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/LATEST/RHEL/glusterfs-rhel8.repo
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Update repositories cache and install "glusterfs-client" package
      package:
        name: glusterfs-client
        update_cache: yes

    # create the directory before mounting the volume
    - file:
        path: "{{mount_point}}"
        state: directory
        mode: 0755

    # Mount the volume on /root/myfiles
    - name: Mount Gluster volume
      mount:
        path: "{{mount_point}}"
        src: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:/{{gluster_cluster_volume}}"
        fstype: glusterfs
        state: mounted
